# Generated by Django 3.2.12 on 2024-04-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocar', '0003_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_efficiency',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Fuel Efficiency (km/litre)'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_automatic',
            field=models.BooleanField(default=True, verbose_name='Is Automatic'),
        ),
        migrations.AddField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default=4, verbose_name='Number of Passengers'),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Gasoline', 'Gasoline')], default='Gasoline', max_length=8, verbose_name='Car Type'),
        ),
    ]
