name: Build and Push Docker image

on:
  push:
    branches: [ main ]  # Set to your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t hanantechvitis/ridex:latest ./myproject/BigCar

    - name: Push Docker image
      run: docker push hanantechvitis/ridex:latest
      
    - name: SSH into EC2 instance 1 and deploy Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull hanantechvitis/ridex:latest

          sudo docker stop some-postgres || true
          sudo docker rm some-postgres || true

          sudo docker run --name some-postgres -e POSTGRES_PASSWORD=12345678 -p 5432:5432 -d postgres
          sudo docker exec hanan02 python3 manage.py makemigrations
          sudo docker exec hanan02 python3 manage.py migrate
          sudo docker exec hanan02 pip3 install requests
          sudo docker exec hanan02 python3 import_cars.py
          
          # Stop and remove the existing Django application container if it exists
          sudo docker stop hanan02 || true
          sudo docker rm hanan02 || true

          
    - name: SSH into EC2 instance 2 and deploy Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_1 }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull hanantechvitis/ridex:latest
          sudo docker start some-postgres || true
          sudo docker stop hanan02 || true
          sudo docker rm hanan02 || true
    - name: Trigger Jenkins Job
      env:
        JENKINS_URL: http://3.127.108.223:8080/job/testing/build
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}  
        JENKINS_USER: ${{ secrets.JENKINS_USER }}  
      run: |
        curl -X POST "$JENKINS_URL" --user "$JENKINS_USER:$JENKINS_TOKEN"
