name: Touch File on Ubuntu

on:
  push:
    branches:
      - main  # Change to your main branch name if differentttttttt

jobs:
  touch_file:
    name: Test Touch File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Touch file on Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            touch file.txt
